<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const VERSIONS = array (
  'doctrine/annotations' => 'v1.4.0@54cacc9b81758b14e3ce750f205a393d52339e97',
  'doctrine/cache' => 'v1.6.1@b6f544a20f4807e81f7044d31e679ccbb1866dc3',
  'doctrine/collections' => 'v1.4.0@1a4fb7e902202c33cce8c55989b945612943c2ba',
  'doctrine/common' => 'v2.7.2@930297026c8009a567ac051fd545bf6124150347',
  'doctrine/dbal' => 'v2.5.12@7b9e911f9d8b30d43b96853dab26898c710d8f44',
  'doctrine/inflector' => 'v1.1.0@90b2128806bfde671b6952ab8bea493942c1fdae',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'doctrine/migrations' => 'v1.3.1@fda27fc96d20a1abd46d4526387c7d6d416da263',
  'doctrine/orm' => 'v2.4.8@5aedac1e5c5caaeac14798822c70325dc242d467',
  'neos/composer-plugin' => '2.0.1@cd20e3c9b548127f4fa1e0f31662072bf82250d4',
  'ocramius/package-versions' => '1.1.2@51e867c70f0799790b3e82276875414ce13daaca',
  'ocramius/proxy-manager' => '2.0.4@a55d08229f4f614bf335759ed0cf63378feeb2e6',
  'psr/log' => '1.0.2@4ebe3a8bf773a19edfe0a84b6585ba3d401b724d',
  'symfony/console' => 'v2.8.22@3ef6ef64abecd566d551d9e7f6393ac6e93b2462',
  'symfony/debug' => 'v3.0.9@697c527acd9ea1b2d3efac34d9806bf255278b0a',
  'symfony/dom-crawler' => 'v2.5.12@3860edcf7ff7e173cfe2151f0d425e610e77cc35',
  'symfony/polyfill-mbstring' => 'v1.4.0@f29dca382a6485c3cbe6379f0c61230167681937',
  'symfony/yaml' => 'v2.5.12@6eb40abc613d80828d55a40811c7a3ca491bc926',
  'typo3/eel' => '3.0.13@b7f7071015411cda7d958193d1a62cea0efc01bb',
  'typo3/flow' => '3.0.13@04c8f9b5141526eba50e05b2adce4fbdf8c3e66a',
  'typo3/fluid' => '3.0.13@5dc1bcc3e398878fae9794fe61e72dece5049abe',
  'typo3/welcome' => '3.0.1@a4ac53cbd849505ce4856275e16f2befbd4ce22c',
  'zendframework/zend-code' => '3.1.0@2899c17f83a7207f2d7f53ec2f421204d3beea27',
  'zendframework/zend-eventmanager' => '3.1.0@c3bce7b7d47c54040b9ae51bc55491c72513b75d',
  'doctrine/instantiator' => '1.0.5@8e884e78f9f0eb1329e445619e04456e64d8051d',
  'flowpack/behat' => 'dev-master@91f18214e1177eeb940be8ce3dbae5908a8656d9',
  'mikey179/vfsStream' => 'v1.5.0@4dc0d2f622412f561f5b242b19b98068bbbc883a',
  'phpdocumentor/reflection-common' => '1.0@144c307535e82c8fdcaacbcfc1d6d8eeb896687c',
  'phpdocumentor/reflection-docblock' => '3.1.1@8331b5efe816ae05461b7ca1e721c01b46bafb3e',
  'phpdocumentor/type-resolver' => '0.2.1@e224fb2ea2fba6d3ad6fdaef91cd09a172155ccb',
  'phpspec/prophecy' => 'v1.7.0@93d39f1f7f9326d746203c7c056f300f7f126073',
  'phpunit/php-code-coverage' => '2.2.4@eabf68b476ac7d0f73793aada060f1c1a9bf8979',
  'phpunit/php-file-iterator' => '1.4.2@3cc8f69b3028d0f96a9078e6295d86e9bf019be5',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '1.0.9@3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
  'phpunit/php-token-stream' => '1.4.11@e03f8f67534427a787e21a385a67ec3ca6978ea7',
  'phpunit/phpunit' => '4.6.10@7b5fe98b28302a8b25693b2298bca74463336975',
  'phpunit/phpunit-mock-objects' => '2.3.8@ac8e7a3db35738d56ee9a76e78a4e03d97628983',
  'sebastian/comparator' => '1.2.4@2b7424b55f5047b47ac6e5ccb20b2aea4011d9be',
  'sebastian/diff' => '1.4.3@7f066a26a962dbe58ddea9f72a4e82874a3975a4',
  'sebastian/environment' => '1.3.8@be2c607e43ce4c89ecd60e75c6a85c126e754aea',
  'sebastian/exporter' => '1.2.2@42c4c2eec485ee3e159ec9884f95b431287edde4',
  'sebastian/global-state' => '1.1.1@bc37d50fea7d017d3d340f230811c9f1d7280af4',
  'sebastian/recursion-context' => '1.0.5@b19cc3298482a335a95f3016d2f8a6950f0fbcd7',
  'sebastian/version' => '1.0.6@58b3a85e7999757d6ad81c787a1fbf5ff6c628c6',
  'typo3/buildessentials' => '3.0.5@10e04102aad6f1248c22484094678f81580684d7',
  'typo3/kickstart' => '3.0.13@913e7f388558dae00ac94ae76c2fd6a8ba66a5d6',
  'webmozart/assert' => '1.2.0@2db61e59ff05fe5126d152bd0655c9ea113e550f',
  'neos/flow-base-distribution' => '1.0.0.0@',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion(string $packageName) : string
    {
        if (! isset(self::VERSIONS[$packageName])) {
            throw new \OutOfBoundsException(
                'Required package "' . $packageName . '" is not installed: cannot detect its version'
            );
        }

        return self::VERSIONS[$packageName];
    }
}
